type: item
name: Overview
id: accessInsightsOverview

feature: redhat_access_insights_reports
rbac:
  feature: redhat_access_insights_reports

parent: accessInsights
href: /redhat_access/insights/
item_type: big_iframe

