type: item
name: Inventory
id: accessInsightsSystems


feature: redhat_access_insights_systems
rbac:
  feature: redhat_access_insights_systems

parent: accessInsights
href: /redhat_access/insights/inventory
item_type: big_iframe
